name: "address_br"
version: "1.0.0"

profile: "address_br"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "shared/macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  address_br:
    +database: address_br
    main:
      raw:
        +materialized: table
      stg:
        +materialized: view
      mart:
        +materialized: table
