address_br:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: address_br
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - spatial
      attach:
        - path: "md:address_br"
          alias: address_br
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: address_br
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - spatial
      attach:
        - path: "md:dev_address_br"
          alias: address_br
          is_ducklake: true
